config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new # create
  end

  def index
    @students = Student.all # Tüm öğrencileri al
  end

  # def show
  #   @student = Student.find(params[:id])
  # end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path, notice: 'Öğrenci başarıyla eklendi.'
    else
      render :new
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path, notice: 'Öğrenci başarıyla silindi.'
  end

  def show
    @student = Student.find(params[:id])
  end
  def edit
    @student = Student.find(params[:id])
    # Düzenleme sayfasını görüntüle
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to students_path, notice: 'Öğrenci başarıyla güncellendi.'
    else
      render :edit
    end
  end


  private
  def student_params
    params.require(:student).permit(:firstname,:lastname)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoproject1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<!-- app/views/students/edit.html.erb -->

<h1>Öğrenci Düzenle</h1>

<%= form_for @student do |f| %>
  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit 'Güncelle' %>
  </div>
<% end %>

<%= link_to 'Geri Dön', students_path %>

app/views/students/index.html.erb
<h1>Student List</h1>

<table>
  <thead>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
  </tr>
  </thead>
  <tbody>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.firstname %></td>
      <td><%= student.lastname %></td>
      <td>
        <%= button_to 'Sil', student_path(student), method: :delete, data: { confirm: 'Emin misiniz?' } %>
      </td>

<!--      <td><%#= link_to 'Düzenle', edit_student_path(student) %></td>-->
      <td>
        <%= button_to 'Düzenle', edit_student_path(student), method: :get, class: 'edit-button' %>
      </td>
      <td colspan="4">
        <%= button_to 'Yeni Öğrenci Ekle', new_student_path, method: :get, class: 'add-button' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1>Yeni Öğrenci Ekle</h1>

<%= form_for @student do |f| %>
  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit 'Ekle' %>
  </div>
<% end %>

<%= link_to 'Geri Dön', students_path %>

app/views/students/show.html.erb
<h1><%= @student.firstname %> <%= @student.lastname %></h1>
<p><strong>Ad:</strong> <%= @student.firstname %></p>
<p><strong>Soyad:</strong> <%= @student.lastname %></p>

<%= link_to 'Back', students_path %>